/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2024-08-16 09:14:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UpdateProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2_1.jar", Long.valueOf(1723607492343L));
    _jspx_dependants.put("/CustomerNavbar.jsp", Long.valueOf(1723798711567L));
    _jspx_dependants.put("jar:file:/D:/miniproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/01-mini-project/WEB-INF/lib/jstl-1.2_1.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
	response.setHeader("Pragma", "no-cache");
	response.setDateHeader("Expires", 0);
	HttpSession sessions = request.getSession(false);
	if (session == null || !"customer".equals(session.getAttribute("customer"))) {

		response.sendRedirect("Index.jsp");
		return;
	}

      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"Customer.jsp\" style=\"color: white;\">Customer Dashboard</a>\r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <form action=\"CustomerController\" method=\"get\" class=\"nav-item\">\r\n");
      out.write("                        <button type=\"submit\" name=\"action\" value=\"Passbook\" class=\"btn btn-link\">Passbook</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <form action=\"CustomerController\" method=\"get\" class=\"nav-item\">\r\n");
      out.write("                        <button type=\"submit\" name=\"action\" value=\"NewTransaction\" class=\"btn btn-link\">New Transaction</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <form action=\"CustomerController\" method=\"get\" class=\"nav-item\">\r\n");
      out.write("                        <button type=\"submit\" name=\"action\" value=\"Update Profile\" class=\"btn btn-link\">Update Profile</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <form action=\"LogoutServlet\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-danger\" style=\"margin-right:12px;\">Logout</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Update Profile</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url('Bank.webp');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("	color: #f8f9fa !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("	color: #e9ecef !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-logout {\r\n");
      out.write("	background-color: #dc3545;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-logout:hover {\r\n");
      out.write("	background-color: #c82333;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".welcome-message {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	height: 70vh;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	padding-left: 20px;\r\n");
      out.write("	font-size: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar .btn-link {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar .btn-link:hover {\r\n");
      out.write("	color: #ffc107;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-profile {\r\n");
      out.write("	background-color: rgba(255, 255, 255, 0.93);\r\n");
      out.write("	color: #000;\r\n");
      out.write("	\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	box-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-profile .card-header {\r\n");
      out.write("	background-color: #343a40;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-profile .card-body {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-profile .form-group {\r\n");
      out.write("	margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-profile .btn {\r\n");
      out.write("	width: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-5\">\r\n");
      out.write("		<div class=\"card card-profile shadow-sm\">\r\n");
      out.write("			<div class=\"card-header\">\r\n");
      out.write("				<h2 class=\"mb-0\">Update Profile</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Form to update first name -->\r\n");
      out.write("				<form action=\"CustomerController\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"firstName\">First Name:</label> \r\n");
      out.write("						<input type=\"text\" class=\"form-control\" pattern=\"[A-Za-z]+\" id=\"firstName\" name=\"firstName\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" name=\"action\" value=\"UpdateFirstName\"\r\n");
      out.write("						class=\"btn btn-primary\">Update First Name</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("				<hr />\r\n");
      out.write("\r\n");
      out.write("				<!-- Form to update last name -->\r\n");
      out.write("				<form action=\"CustomerController\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"lastName\">Last Name:</label> \r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"lastName\" pattern=\"[A-Za-z]+\" name=\"lastName\"\r\n");
      out.write("							value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" name=\"action\" value=\"UpdateLastName\"\r\n");
      out.write("						class=\"btn btn-primary\">Update Last Name</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("				<hr />\r\n");
      out.write("\r\n");
      out.write("				<!-- Form to update password -->\r\n");
      out.write("				<form action=\"CustomerController\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"oldPassword\">Old Password:</label> \r\n");
      out.write("						<input type=\"password\" class=\"form-control\" id=\"oldPassword\"\r\n");
      out.write("							name=\"oldPassword\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"newPassword\">New Password:</label> \r\n");
      out.write("						<input type=\"password\" class=\"form-control\" id=\"newPassword\"\r\n");
      out.write("							name=\"newPassword\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"confirmNewPassword\">Confirm New Password:</label> \r\n");
      out.write("						<input type=\"password\" class=\"form-control\" id=\"confirmNewPassword\"\r\n");
      out.write("							name=\"confirmNewPassword\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" name=\"action\" value=\"UpdatePassword\"\r\n");
      out.write("						class=\"btn btn-primary\">Update Password</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap JavaScript and dependencies -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
